### ISSUE TITLE
token undefined error

### ISSUE THREAD

**Issue by answerquest** [mapbox/mvtview#11]
I'm trying to read a .mvt tile generated from https://github.com/tobinbradley/dirt-simple-postgis-http-api 

Getting this error:

```
$ mvtview 14_11761_6907.mvt
/usr/local/lib/node_modules/@mapbox/mvtview/cli.js:17
if (!token.includes('pk.')) {
           ^

TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/@mapbox/mvtview/cli.js:17:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by ghost** [comment]
You can work around this issue by setting the env var that [cli.js](https://github.com/mapbox/mvtview/blob/88a440ea2c31fa500fb9cc67dfd7896fa8e67b6e/cli.js#L16) expects to a Mapbox token, e.g. `MapboxAccessToken='pk....' mvtview path/to/file.mvt`, however after I get past this I just get a different error 😢

**Comment by kolisko** [comment]
+1
