### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by pyrog** [mapbox/mvtview#8]
download https://water-map.org/gridFountain/fullgrid2_0003_0045_0006_0048.json

```
#build vector tiles
tippecanoe -f -zg --drop-densest-as-needed in.geojson -e water-map fullgrid2_0003_0045_0006_0048.json

#display one tile
mvtview water-map/6/33/22.pbf
```

mvtview display the following errors:
```
(node:28422) UnhandledPromiseRejectionWarning: Error: Unimplemented type: 3
    at Pbf.skip (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/pbf/index.js:211:20)
    at Pbf.readFields (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/pbf/index.js:46:45)
    at new VectorTileLayer (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/@mapbox/vector-tile/lib/vectortilelayer.js:20:9)
    at readTile (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/@mapbox/vector-tile/lib/vectortile.js:13:21)
    at Pbf.readFields (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/pbf/index.js:44:13)
    at new VectorTile (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/@mapbox/vector-tile/lib/vectortile.js:8:23)
    at Object.makeStyle (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/utils.js:18:12)
    at app.get (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/mvtview.js:20:13)
    at Layer.handle [as handle_request] (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/express/lib/router/layer.js:95:5)
    at next (.nvm/versions/node/v8.17.0/lib/node_modules/@mapbox/mvtview/node_modules/express/lib/router/route.js:137:13)
(node:28422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28422) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by MichielMortier** [comment]
I had the same problem, it's cause because your .pbf is probably gzipped. Use tippecanoe with the --no-tile-compression option to generate unzipped pbf files.
